# Generated by Django 3.0.7 on 2020-08-23 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='amnt',
            field=models.IntegerField(default=0),
        ),
    ]
