# Generated by Django 3.0.7 on 2020-08-23 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_contact_amnt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='amnt',
        ),
        migrations.AlterField(
            model_name='orders',
            name='amnt',
            field=models.IntegerField(default=0),
        ),
    ]
