# Generated by Django 3.0.7 on 2021-04-10 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200823_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerDetails',
            fields=[
                ('seller_id', models.AutoField(primary_key=True, serialize=False)),
                ('bookname', models.CharField(max_length=90)),
                ('bookauthor', models.CharField(max_length=30)),
                ('bookcategory', models.CharField(max_length=30)),
                ('usedtime', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('longi', models.CharField(max_length=30)),
                ('latt', models.CharField(max_length=30)),
                ('img1', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
