# Generated by Django 3.0.7 on 2021-04-10 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_sellerdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerdetails',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
