# Generated by Django 3.0.7 on 2021-05-28 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20210528_0859'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerDetails',
            fields=[
                ('buyer_id', models.AutoField(primary_key=True, serialize=False)),
                ('bookname', models.CharField(max_length=50)),
                ('bookauthor', models.CharField(max_length=50)),
                ('bookcategory', models.CharField(max_length=50)),
                ('longi', models.CharField(max_length=50)),
                ('latt', models.CharField(max_length=50)),
            ],
        ),
    ]
